### PR TITLE
solved issue #38

### PR DESCRIPTION
**Pull request by felixoder**
solved the issue mentioned in #38

### CODE REVIEW

**Comment by utk2103** [comment]
Attach some screenshots to see the changes you have made.

**Comment by felixoder** [comment]
@utk2103 
previously the member section was like 
image
and I aligned the items with the scroller view 
image
I think this will help fs

**Comment by felixoder** [comment]
if this PR got merged then I will raise a issue about the footer buffer in the small devices 
image
assign me that asap after that. Thanks

**Comment by felixoder** [comment]
and plz add "hactoberfest-accepted" label on the PR

**Comment by utk2103** [comment]
i merged the pr and assigned it to you with label on the issue section @felixoder

**Review by utk2103 — APPROVED** [review]

**Pull request merged**
